UniSet.py: Don't fail when a type doesn't have __module__
Seems like only heap types from C extensions can possibly have this.
You cannot delete a python-defined type's __module__ attribute
directly, or delete from its dict proxy:

>>> typ = type('Test', (), {})
>>> del typ.__module__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: can't delete Test.__module__
>>> del typ.__dict__['__module__']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'mappingproxy' object does not support item deletion

Don't think there's a way to add a test for this without writing
another C extension.

Fixes #35