stdtypes.c: Use co_nlocalsplus instead of stacktop for locals
The interpreter sometimes sets stacktop to bad values. Not exactly
sure why, but it causes assertion in test_Classifiers.test_classification

  =====================================================================
  ERROR: test_classification (guppy.heapy.test.test_Classifiers.ClassificationCase.test_classification)
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "guppy3/guppy/heapy/View.py", line 423, in obj_at
      return self.immnodeset(self.hv.heap()).obj_at(addr)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ValueError: No object found at address 0x7f8d7aa1b540

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "guppy3/guppy/heapy/test/test_Classifiers.py", line 906, in test_classification
      self.aseq(iso(o).byid.kind, Use.Id(id(o)))
                                  ^^^^^^^^^^^^^
    File "guppy3/guppy/heapy/UniSet.py", line 25, in __call__
      def __call__(self, *args, **kwds): return self.fam.c_call(self, args, kwds)
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "guppy3/guppy/heapy/UniSet.py", line 1938, in c_call
      return a.classifier.get_userkind(*args, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "guppy3/guppy/heapy/Classifiers.py", line 237, in get_userkind
      return self.get_kind(self.mod.View.obj_at(address))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "guppy3/guppy/heapy/View.py", line 425, in obj_at
      raise ValueError('No object found at address %s' % hex(addr))
  ValueError: No object found at address 0x7f8d7aa1b540