bitset.c: Fix overflow in mutbitset_iop_PyLongObject
PyLong_AsDouble may encounter:
  OverflowError: int too large to convert to float
Workaround with PyLong_AsLongAndOverflow